### PR TITLE
Glossary and links not live added

### PR DESCRIPTION
**Pull request by GeorgeKerscher**
I pasted in the suggestion from Avneesh. The only change there was to ad a ul and li for the term. This is similar to the bibliography.

Also added a paragraph that the links and references are not live.

This will also mean that Gregorio's build of theEPUB should be updated.

### CODE REVIEW

**Review by gregoriopellegrino — APPROVED** [review]

**Comment by gregoriopellegrino** [comment]
Fine for me. When merged, I'll update the EPUB.

**Review by clapierre — APPROVED** [review]
I assume we didn't want to use `<DD> <DT>` here for a reason?

**Comment by GeorgeKerscher** [comment]
I would be happy to use DL, should I make that change and then merge it so we can get this done?

**Comment by mattgarrish** [comment]
Does the content of the section matter, or are you only testing the dpub-aria roles?

The definitions are supposed to be identifiable within the glossary, so either a list with term and definitions or a definition list works fine in that regard. Definition lists are probably more common, but if you don't care about those roles then it's a coin flip.

**Comment by clapierre** [comment]
Thanks @mattgarrish we are just testing the dpub-aria roles, so it sounds like we can just leave this as is for now as it isn't that important as Matt says its a coin flip. So lets merge @GeorgeKerscher :)

**Comment by avneeshsingh** [comment]
Looks good George. It looks that it is ready to go.

**Pull request merged**
