### PR TITLE
Convert documents to respec

### PR DESCRIPTION
**Pull request by mattgarrish**
Adds the respec metadata so the documents format with DAISY branding.

### CODE REVIEW

**Review by clapierre — COMMENTED** [review]
I see you added the logo but it still is linked to your repo Matt.
src: 'https://mattgarrish.github.io/transitiontoepub/daisy_high.jpg',

**Comment by mattgarrish** [comment]
Ya, I wasn't able to reference the logo on the daisy site due to cors issues so had to add a local copy. In the interests of easily reusing the metadata elsewhere, I've updated the paths to be root relative rather than absolute (i.e., it will work anywhere there's an images directory with the file in the root of the repository).

But it means you will only see the logo if you serve the file from localhost while editing locally. I don't figure that's too big an issue.

**Review by clapierre — APPROVED** [review]
works for me thanks Matt!

**Comment by clapierre** [comment]
Will merge this so we have the new ReSpec infrastructure and then will add in contributors etc.

**Pull request merged**
