### PR TITLE
Updated acknowledgements

### PR DESCRIPTION
**Pull request by mattgarrish**
Adds lists of people based on contributions and also adds additional people to list of contributors. I've only added a placeholder for a dedication.

I've split the acknowledgements into a separate file so you don't have to maintain it twice. Respec imports it into the best practice documents.

### CODE REVIEW

**Review by clapierre — COMMENTED** [review]
Looks good. Although I am not sure if the same people were involved in the Extended descriptions as were for the mathML documents.

**Comment by mattgarrish** [comment]
Ah, I thought this was one group responsible for both. Feel free to modify the PR to whatever makes more sense.

**Comment by GeorgeKerscher** [comment]
I do not how we would  determine who did what. I suggest we leave them the same. We would cover the topics on the same TIES call.

**Review by avneeshsingh — COMMENTED** [review]
The list looks good to me. We can merge it for tomorrow's TIES call. If some more changes are required in acknowledgements, we can do another commit.
Regarding Charles comment for different set of people involved in extended descriptions and Math best practices. The two additional names involved in Math best practices were Neil and Sina. If we want to include them in contributers for techniques, it would be fine.

**Pull request merged**
